name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: xdebug
        ini-values: variables_order="EGPCS"

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      env:
<<<<<<< HEAD
        SIAT_CODIGO_SISTEMA: ${{ secrets.SIAT_CODIGO_SISTEMA }}
        SIAT_NIT: ${{ secrets.SIAT_NIT }}
        SIAT_USER: ${{ secrets.SIAT_USER }}
        SIAT_PASSWORD: ${{ secrets.SIAT_PASSWORD }}
=======
        CODIGO_SISTEMA: ${{ secrets.CODIGO_SISTEMA }}
        NIT: ${{ secrets.NIT }}
        USER: ${{ secrets.USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
>>>>>>> 93a4328 (resolve #13 solicitud cufd)
      run: composer run-script test

    - name: Run code sniffer
      run: composer run-script lint
